### ISSUE TITLE
par2deep-cli in v1.9.4 par2deep object throws no attribute 'unused'

### ISSUE THREAD

**Issue by jonochang** [brenthuisman/par2deep#13]
Error occurs in this line:
https://github.com/brenthuisman/par2deep/blob/1e6ac4c3bf7b99382ac68f5bb75629ea55a6204b/par2deep/cli.py#L49

Looks like the CLI hasn't kept up with changes in the Par2Deep object which tracks separate orphan object arrays instead of unused.

**Comment by brenthuisman** [comment]
Good catch! I don't really use the cli anymore. Let me know if it was fixed/if you find more bugs!
