### ISSUE TITLE
[bug] libpar2: 2GB limit

### ISSUE THREAD

**Issue by brenthuisman** [brenthuisman/par2deep#16]
Alternatives: a good and current(ish) list available at https://github.com/animetosho/ParPar/blob/master/benchmarks/info.md
Having a speed bump is nice, but phpar2, par2j are Windows only, would have to port... Parpar itself is create only and written in javascript, therefore not an option.

Candidates:
- Gopar
  - cross-compile is easy
  - will need to verify if it has a 2GB file limit
  - seems to read files into memory, so unsuitable for very large files (not an issue for me)
  - has fewer flags (e.g. can't create by percentage)
    - solved in 1.9.5: only diff with par2 is that gopar wants a space between flag and argument. also gopar does not have or need `-B`
  - does not use return values to indicate type of problem (just fail or succeed)
- par2cmdline-tbb
  - 2GB limit fixed
  - not significantly faster
  - requires Intel TBB
  - no longer maintained
  - source only available as part of other project: https://github.com/jcfp/par2tbb-chuchusoft-sources/releases/

**Comment by brenthuisman** [comment]
Alternatives: a good and current(ish) list available at https://github.com/animetosho/ParPar/blob/master/benchmarks/info.md
Having a speed bump is nice, but phpar2, par2j are Windows only, would have to port... Parpar itself is create only and written in javascript, therefore not an option.

Candidates:
- Gopar
  - cross-compile is easy
  - having some issues getting it to build, will need to verify if it has a 2GB file limit
  - seems to read files into memory, so unsuitable for very large files (not an issue for me)
- par2cmdline-tbb
  - 2GB limit fixed
  - not significantly faster
  - requires Intel TBB
  - no longer maintained
  - source only available as part of other project: https://github.com/jcfp/par2tbb-chuchusoft-sources/releases/

**Comment by nikitakretov** [comment]
It appears that Animetosho's par2cmdline-turbo (  https://github.com/animetosho/par2cmdline-turbo ) solves both the 2GB file limit problem and UTF-8 support problem. And it is a drop-in replacement for par2cmdline. Hope it helps.

**Comment by brenthuisman** [comment]
I've just created a new release, v1.10, which I believe addresses this issue (since it includes par2cmdline-turbo which really contains the fix). Let me know if it didn't.
