### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by jamesbearclaw** [brenthuisman/par2deep#2]
It would be nice to have a "Profile" drop down list on the config page so that we could load/save preset options per directory.  Some directories I'd want 5% and some I'd want 100% (when that change is made).

**Comment by brenthuisman** [comment]
The readme explains how this is currently handled by having an ini/dotfile in each dir you wish to check:

https://github.com/brenthuisman/par2deep#usage

**Comment by brenthuisman** [comment]
Today's small update allows you to set the protection to 100%.
