### ISSUE TITLE
Allow hiding parity files

### ISSUE THREAD

**Issue by proItheus** [brenthuisman/par2deep#25]
I'm not so happy with many `*.par2`, `*.vol*.par2` files cluttering my file browser view...

Maybe we can add an option to prefix `.` to .par files, so that they are all hidden. e.g. for a directory like
> file1
.file2

After running `par2deep-cli --hide-parity-files`
>file1
.file1.par2
.file1.vol000+100.par2
.file2
..file2.par2
..file2.vol000+100.par2

**Comment by brenthuisman** [comment]
I share your distaste, but as explored [here](https://github.com/brenthuisman/par2deep/issues/4), support for alternative locations for parity files isn't consistent across implementations, and not even within (at the time) `par2cmdline` itself. I had my hopes up for Gopar, but it has some other outstanding bugs and development seems to have ceased, so I don't see a solution other than instructing your file browser to hide them.
