### ISSUE TITLE
Option to store parity files in another folder or a subfolder to tidy up things a bit and allow a centralized parity archive

### ISSUE THREAD

**Issue by dia3olik** [brenthuisman/par2deep#27]
Hey @brenthuisman

First of all thanks a lot for par2deep!

I think a very handy addition would be the option to store the par2 files and raw parity data files in another folder or a subfolder instead of alongside the files to protect...

This option could be set inside the par2deep.ini file or passed via a command line option...like -pardir DIRECTORY for example.

I understand that being a recursive utility it could lead to conflicts if used a subfolder but maybe automatically adding the folder with all the par2 files and parity data to exclusions if  would solve this cleanly...
Or if it's tricky maybe just using a fixed subfolder called something like P2D_PARITY which is always ignored?

The customisable option would be much better of course because could enable users to have for example a centralized "parity archive" if they prefer it so get additional functionality with this feature, not only being able to have cleaner directories.

This would be extremely useful I think when dealing with a directory already filled with thousands of files, to keep things separate when needed/preferred ;-)

What do you think?

**Comment by brenthuisman** [comment]
It's a good idea (and would have my personal preference as well), and it was discussed and attempted, but since behavior of the relevant flag wasn't consistent across implementations, I removed the option: https://github.com/brenthuisman/par2deep/issues/25
